Location/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('measurements.urls'))
]

measurements/urls.py
from django.urls import path

from measurements.views import calculate_distance

app_name = 'measurements'

urlpatterns = [
    path('', calculate_distance, name='calculate-distance')
]

measurements/models.py
from django.db import models

# Create your models here.


class Measurement(models.Model):
    location = models.CharField(max_length=200)
    destination = models.CharField(max_length=200)
    distance = models.DecimalField(max_digits=10, decimal_places=2)

    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Distance from {self.location} to {self.distance} is {self.distance} km"

measurements/forms.py
from django import forms

from measurements.models import Measurement


class MeasurementModelForm(forms.ModelForm):
    destination = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset'\
            ' ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600'\
            ' sm:text-sm sm:leading-6'
    }))
    class Meta:
        model = Measurement
        fields = ('destination',)

measurements/views.py
from django.shortcuts import render, get_object_or_404

from measurements.forms import MeasurementModelForm
from measurements.models import Measurement


def calculate_distance(request):
    obj = get_object_or_404(Measurement, id=1)
    form = MeasurementModelForm()

    context = {
        'distance': obj,
        'form': form
    }
    return render(request, 'measurements/main.html', context)

measurements/templates/measurements/main.html
{% extends 'base.html' %}

{% block content %}
<div class="max-w-4xl m-auto mt-10">
    <form action="" method="POST">
        <div class="col-span-full">
            <label for="id_destination" class="block text-sm font-medium leading-6 text-gray-900">Street</label>
            <div class="mt-2">
                {{ form.destination }}
            </div>
            <div class="mt-2">
                <button type="button" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">Default</button>
            </div>
        </div>        
    </form>
</div>
{% endblock content %}

templates/base.html
<!doctype html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.tailwindcss.com"></script>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.4/flowbite.min.css" rel="stylesheet" />
  <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    <div class="container m-auto">
        {% block content %}{% endblock content %}
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.4/flowbite.min.js"></script>
</body>
</html>